### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by neo210211** [OYIon/LiveSharp#67]
I have been wanting to buy a license for **LiveSharp**. However, the experience of using it has been rather _frustrating_ lately -- it's almost _unusable_ to me without fixing the above issue. I am on the latest version of **LiveSharp**.

By simply updating the following method of my ContentPage, I am encountering **System.InvalidOperationException**.

```
        private View NewTimestamp()
        {
            var ret = new Label
                        {
                            HorizontalOptions = LayoutOptions.End,
                            FontSize          = 14,
                            FontAttributes    = FontAttributes.None
                        }
                        .Row(ItemTemplateRow.R0)
                        .Column(ItemTemplateColumn.Date)
                        .Bind(Label.TextProperty,
                                "LatestMessage.DateTimeUtc",
                                convert: (DateTime dateTimeUtc) =>
                                {
                                    var str = DateTime.Today.Equals(dateTimeUtc.Date)
                                            ? "t"
                                            : "d";
                                    var cti = new CultureInfo("en-GB");
                                    var dte = dateTimeUtc.ToString(str, cti);
                                    var ret = $"{dte}";

                                    return ret;
                                });

            return ret;
        }
```

The following shows the messages emitted in the Debug window of Visual Studio 2019.

```
[0:] livesharp: received QunFa.Views.MessagesPage NewTimestamp 
Loaded assembly: /private/var/containers/Bundle/Application/53B8516A-B9DF-4DEA-957F-2EAAE1CB79C2/QunFa.iOS.app/System.Linq.Expressions.dll [External]
2020-05-14 14:30:09.298 QunFa.iOS[22867:7094284] System.InvalidOperationException: No coercion operator is defined between types 'System.String' and 'Xamarin.Forms.Label'.
  at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow (System.Linq.Expressions.ExpressionType coercionType, System.Linq.Expressions.Expression expression, System.Type convertToType) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:432 
  at System.Linq.Expressions.Expression.Convert (System.Linq.Expressions.Expression expression, System.Type type, System.Reflection.MethodInfo method) [0x00051] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:779 
  at System.Linq.Expressions.Expression.Convert (System.Linq.Expressions.Expression expression, System.Type type) [0x00000] in /Library
/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:753 
  at LiveSharp.Runtime.ExpressionDeserializer.CoerceExpression (System.Linq.Expressions.Expression expr, System.Type destinationType) [0x00251] in <30134bc9b80f49a0acda62e290be6c95>:0 
**LiveSharp.Runtime.ExpressionDeserializer+DeserializationException:** 'Deserialization failed for: 
<Assign>
  <Parameter>
    <Type Assembly="netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51">
      <S>System</S>
      <S>String</S>
    </Type>
    <S>ret</S>
  </Parameter>
  <Call>
    <Null />
    <MethodInfo>
      <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
        <S>System</S>
        <S>String</S>
      </Type>
      <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
        <S>System</S>
        <S>String</S>
      </Type>Format<Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"><S>System</S><S>String</S></Type><Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"><S>System</S><S>Object[]</S></Type></MethodInfo>
    <Array>
      <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
        <S>System</S>
        <S>Object</S>
      </Type>
      <Constant>
        <Value>
          <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
            <S>System</S>
            <S>String</S>
          </Type>
          <S>{0} </S>
        </Value>
      </Constant>
      <NewArrayInit>
        <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
          <S>System</S>
          <S>Object</S>
        </Type>
        <Array>
          <Type Assembly="System.Linq.Expressions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
            <S>System.Linq.Expressions</S>
            <S>Expression</S>
          </Type>
          <Convert>
            <Variable>
              <Type Assembly="netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51">
                <S>System</S>
                <S>String</S>
              </Type>dte</Variable>
            <Type Assembly="System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e">
              <S>System</S>
              <S>Object</S>
            </Type>
          </Convert>
        </Array>
      </NewArrayInit>
    </Array>
  </Call>
</Assign>'
```

**Comment by ionoy** [comment]
Thanks for the feedback @neo210211 

I have released a beta version of the new LiveSharp recently. The backend is now based on IL, so there shouldn't be any `DeserializationException`s. 

Server: https://github.com/OYIon/LiveSharp/releases/tag/1.5-beta
NuGet: https://www.nuget.org/packages/LiveSharp/ (make sure to install prerelease version)

Please tell me if it resolves your issue

Thanks!

**Comment by neo210211** [comment]
I have just tried. I am afraid it doesn't resolve the issue. It has actually crashed my app. Please help.

**Comment by ionoy** [comment]
Can you please post the exception details?

**Comment by neo210211** [comment]
Here you go...

```
System.Linq.Expressions
Expression.GetUserDefinedCoercionOrThrow (System.Linq.Expressions.ExpressionType coercionType, System.Linq.Expressions.Expression expression, System.Type convertToType) /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:432
System.Linq.Expressions
Expression.Convert (System.Linq.Expressions.Expression expression, System.Type type, System.Reflection.MethodInfo method) /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:779
System.Linq.Expressions
Expression.Convert (System.Linq.Expressions.Expression expression, System.Type type) /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Linq.Expressions/src/System/Linq/Expressions/UnaryExpression.cs:753
LiveSharp.Runtime.IL
CompilerHelpers.Coerce (System.Linq.Expressions.Expression expr, System.Type targetType)
LiveSharp.Runtime.IL
IlExpressionCompilerHandlers.CallImpl (LiveSharp.Runtime.IL.InstructionContext ctx, System.Boolean isVirtualCall)
LiveSharp.Runtime.IL
IlExpressionCompilerHandlers.Call (LiveSharp.Runtime.IL.InstructionContext ctx)
LiveSharp.Runtime.IL
IlExpressionCompiler.CompileInstruction (LiveSharp.Runtime.IL.InstructionContext instructionContext)
LiveSharp.Runtime.IL
CompilerContext.Compile (LiveSharp.Runtime.IL.IlInstruction instruction, LiveSharp.Runtime.Infrastructure.ImmutableStack`1[T] stack)
LiveSharp.Runtime.IL
CompilerContext.CompileBranch (System.Int32 instructionIndex)
LiveSharp.Runtime.IL
CompilerContext.<CompileInstructions>g__compileBranch|31_0 (System.Int32 index)
LiveSharp.Runtime.IL
CompilerContext.CompileInstructions ()
LiveSharp.Runtime.IL
IlExpressionCompiler.GetExpression (System.Boolean enableDebugging, System.Type delegateType)
LiveSharp.Runtime.IL
MethodMetadata.CreateDelegate (System.Object instance, System.Type delegateType)
LiveSharp.Runtime
LiveSharpRuntime.Execute (System.Object methodBody, System.Object thisInstance, System.Object[] arguments)
LiveSharp.Runtime
LiveSharpRuntime.Execute (System.Object methodBody, System.Object thisInstance, System.Int32 argCount, System.Object arg0, System.Object arg1, System.Object arg2, System.Object arg3, System.Object arg4, System.Object arg5, System.Object arg6, System.Object arg7, System.Object arg8, System.Object arg9, System.Object arg10, System.Object arg11)
QunFa.Views
MessagesPage+<>c.<NewTimestamp>b__5_0 (System.DateTime dateTimeUtc) C:\Users\xxx\Documents\GitHub\QunFa\QunFa\Views\MessagesPage.cs:125
Xamarin.Forms.Markup
FuncConverter`3[TSource,TDest,TParam].Convert (System.Object value, System.Type targetType, System.Object parameter, System.Globalization.CultureInfo culture) D:\a\1\s\Xamarin.Forms.Core\Markup\FuncConverter.cs:30
Xamarin.Forms
Binding.GetSourceValue (System.Object value, System.Type targetPropertyType) D:\a\1\s\Xamarin.Forms.Core\Binding.cs:289
Xamarin.Forms
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:144
Xamarin.Forms
BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:72
Xamarin.Forms
Binding.Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged) D:\a\1\s\Xamarin.Forms.Core\Binding.cs:136
Xamarin.Forms
BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:480
Xamarin.Forms
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:209
Xamarin.Forms
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) D:\a\1\s\Xamarin.Forms.Core\Element.cs:467
Xamarin.Forms
Element.<OnBindingContextChanged>b__82_0 (Xamarin.Forms.BindableObject child, System.Object bc) D:\a\1\s\Xamarin.Forms.Core\Element.cs:308
Xamarin.Forms
BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext)
Xamarin.Forms
Element.OnBindingContextChanged () D:\a\1\s\Xamarin.Forms.Core\Element.cs:306
Xamarin.Forms
VisualElement.OnBindingContextChanged () D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:758
Xamarin.Forms
View.OnBindingContextChanged () D:\a\1\s\Xamarin.Forms.Core\View.cs:158
Xamarin.Forms
Grid.OnBindingContextChanged () D:\a\1\s\Xamarin.Forms.Core\Grid.cs:147
Xamarin.Forms
BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:500
Xamarin.Forms
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:463
Xamarin.Forms
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397
Xamarin.Forms
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334
Xamarin.Forms
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311
Xamarin.Forms
BindableObject.set_BindingContext (System.Object value) D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:41
Xamarin.Forms.Platform.iOS
TemplatedCell.Bind (Xamarin.Forms.DataTemplate template, System.Object bindingContext, Xamarin.Forms.ItemsView itemsView) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\TemplatedCell.cs:90
Xamarin.Forms.Platform.iOS
ItemsViewController`1[TItemsView].UpdateTemplatedCell (Xamarin.Forms.Platform.iOS.TemplatedCell cell, Foundation.NSIndexPath indexPath)
Xamarin.Forms.Platform.iOS
ItemsViewController`1[TItemsView].GetCell (UIKit.UICollectionView collectionView, Foundation.NSIndexPath indexPath)
Xamarin.Forms.Platform.iOS
ItemsViewController`1[TItemsView].GetPrototype ()
Xamarin.Forms.Platform.iOS
ItemsViewLayout.DetermineCellSize () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewLayout.cs:211
Xamarin.Forms.Platform.iOS
ListViewLayout.ConstrainTo (CoreGraphics.CGSize size) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ListViewLayout.cs:16
Xamarin.Forms.Platform.iOS
ItemsViewController`1[TItemsView].ViewWillLayoutSubviews ()
Xamarin.Forms.Platform.iOS
StructuredItemsViewController`1[TItemsView].ViewWillLayoutSubviews ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIKit
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86
UIKit
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65
QunFa.iOS
Application.Main (System.String[] args) C:\Users\xxx\Documents\GitHub\QunFa\QunFa.iOS\Main.cs:38
```

**Comment by ionoy** [comment]
Please try 1.5.11-beta NuGet package. If it still fails, please copy the whole exception text here. (make sure to remove any sensitive data if there is some)

Thanks!

**Comment by neo210211** [comment]
Hi!

Using `LiveSharp.ServerApp.Setup.1.0.0.exe` and `LiveSharp 1.5.11-beta`, my app can no longer connect to the LiveSharp Server even with Firewall being turned off.

Please advise.


```
[0:] livesharp: error: Connection exception: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 <---
[0:] livesharp: Connecting to host 192.168.68.129:52540
[0:] livesharp: error: Connection exception: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 <---
[0:] livesharp: Connecting to host 192.168.68.129:54540
[0:] livesharp: error: Connection exception: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:1214 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:538 <---
[0:] livesharp: Connecting to host 192.168.68.129:56540

```

**Comment by ionoy** [comment]
You'll need to reinstall the server app too: https://github.com/OYIon/LiveSharp/releases/tag/1.5-beta (I have updated it today)

**Comment by neo210211** [comment]
I just installed and tested it again. Unfortunately, the problem persists.

Please help.

**Comment by neo210211** [comment]
I uninstalled all previous versions of the Server and installed 1.5-beta. Still, the problem continues.

**Comment by ionoy** [comment]
Is it still the connection issue?

**Comment by neo210211** [comment]
Still the connection issue.

**Comment by ionoy** [comment]
Can you check the logs? The location is `%TEMP%\LiveSharp`

Also, can you come to https://gitter.im/LiveSharp/Lobby (@ionoy)? It would be easier to solve the issue interactively. Thanks!
